0:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
1:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
2:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
3:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
4:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
5:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
6:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
7:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
8:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
9:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
10:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
11:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
12:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
13:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
14:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
15:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
16:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
17:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
18:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
19:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
20:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
21:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
22:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
23:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
24:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
25:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
26:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
27:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
28:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
29:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
30:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4
31:
  0:
    nbits_key: 8
    nbits_value: 4
  1:
    nbits_key: 8
    nbits_value: 4
  2:
    nbits_key: 8
    nbits_value: 4
  3:
    nbits_key: 8
    nbits_value: 4
  4:
    nbits_key: 8
    nbits_value: 4
  5:
    nbits_key: 8
    nbits_value: 4
  6:
    nbits_key: 8
    nbits_value: 4
  7:
    nbits_key: 8
    nbits_value: 4